# Task - 1 problem - 1

In [13]:
def div(a): # function creation
    
    try:
        x = 5 / a
        print("Value of x: ",x)
    except:
        print("Input value is given as zero, which is not divisiable by zero.")

while True:
    try :
        value = int(input("Enter any integer: "))
    except (ValueError) as e:
        print(e)
        print()
        continue
    else:
        print("...Given input value is integer... ")
        print()
        break
    
# calling function
div(value)    

Enter any integer: fgfg
invalid literal for int() with base 10: 'fgfg'

Enter any integer: ghgh
invalid literal for int() with base 10: 'ghgh'

Enter any integer: 2
...Given input value is integer... 

Value of x:  2.5


# Task - 1 problem - 2

In [15]:
subject = ["Americans", "Indians"]
verbs = ["play", "watch"]
objects = ["Basketball", "Cricket"]

print("Given No.of list as Input: ",subject, verbs, objects)
for r in subject:
    for k in verbs:
        for l in objects:
            print(r+" "+k+" "+l)

Given No.of list as Input:  ['Americans', 'Indians'] ['play', 'watch'] ['Basketball', 'Cricket']
Americans play Basketball
Americans play Cricket
Americans watch Basketball
Americans watch Cricket
Indians play Basketball
Indians play Cricket
Indians watch Basketball
Indians watch Cricket


# Task - 2 problem - 1

In [17]:
import numpy as np

def my_vander_gen(input_vector, N, increasing): # function definition 
    
    if increasing == False: # condition to give outpu in decreasing order
        opt_matrix = np.array([ind ** (N - 1 - i) for ind in input_vector for i in range(N)]).reshape(input_vector.size, N)
    else:
        opt_matrix = np.array([ind ** i for ind in input_vector for i in range(N)]).reshape(input_vector.size, N)
    
    return opt_matrix
    
input_vector = np.array([1,2,3,5]) # input array
N = 3  # power to give element wise 
out_matrix_dec = my_vander_gen(input_vector, N, False) # calling function

print("Given array as input: ",input_vector)
print("\nNo of columns in output matrix should be: ",N)
print("\nA.T.VanderMonde Matrix generation by input array in decreasing order: \n",out_matrix_dec)

Given array as input:  [1 2 3 5]

No of columns in output matrix should be:  3

A.T.VanderMonde Matrix generation by input array in decreasing order: 
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
